"""Account-scoped V6 associative memory brain."""

from .bootstrap import (
    BOT_DIR_NAME,
    LAYOUT_VERSION,
    LEGACY_MEMORY_FILENAMES,
    account_data_dir,
    account_db_path,
    bot_data_dir,
    bootstrap_accounts,
    cleanup_legacy_memory_files,
    layout_marker_path,
    legacy_account_dir,
)
from .gateway import EmbeddingBatch, MemoryModelGateway
from .ingestion import (
    bangumi_episode_observation,
    bot_action_observation,
    comment_observation,
    text_observation,
    video_observation,
)
from .models import (
    ActivityMemoryError,
    ArchiveResult,
    BootstrapResult,
    ClaimedJob,
    CleanupRecord,
    HealthReport,
    IdempotencyConflictError,
    MemoryBrainError,
    Observation,
    ObservationEnvelope,
    ProviderNotConfigured,
    ReingestBlockedError,
    SourceDocument,
    VectorDimensionError,
)
from .store import (
    MemoryBrainStore,
    build_fts_text,
    chunk_text,
    decode_vector,
    encode_vector,
    normalize_entity_type,
    normalize_search_text,
    normalize_vector,
)
from .recall import RecallQuery, RecallResult, RetrievalPolicy, policy_for_mode
from .redaction import PrivateMessageRedactor, RedactionResult
from .service import ActivityMemoryContext, MemoryBrainService
from .worker import PersistentMemoryWorker, WorkerRunReport

__all__ = [
    "ActivityMemoryContext",
    "ActivityMemoryError",
    "ArchiveResult",
    "BootstrapResult",
    "ClaimedJob",
    "CleanupRecord",
    "EmbeddingBatch",
    "HealthReport",
    "IdempotencyConflictError",
    "BOT_DIR_NAME",
    "LAYOUT_VERSION",
    "LEGACY_MEMORY_FILENAMES",
    "MemoryBrainError",
    "MemoryBrainService",
    "MemoryBrainStore",
    "MemoryModelGateway",
    "Observation",
    "ObservationEnvelope",
    "PersistentMemoryWorker",
    "PrivateMessageRedactor",
    "ProviderNotConfigured",
    "ReingestBlockedError",
    "RecallQuery",
    "RecallResult",
    "RetrievalPolicy",
    "RedactionResult",
    "policy_for_mode",
    "SourceDocument",
    "VectorDimensionError",
    "WorkerRunReport",
    "account_data_dir",
    "account_db_path",
    "bangumi_episode_observation",
    "bot_data_dir",
    "bootstrap_accounts",
    "build_fts_text",
    "bot_action_observation",
    "chunk_text",
    "comment_observation",
    "cleanup_legacy_memory_files",
    "decode_vector",
    "encode_vector",
    "layout_marker_path",
    "legacy_account_dir",
    "normalize_entity_type",
    "normalize_search_text",
    "normalize_vector",
    "text_observation",
    "video_observation",
]
